<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'example\\framework\\database\\databasetestcase' => '/DatabaseTestCase.php',
                'example\\framework\\event\\anotherdummyevent' => '/AnotherDummyEvent.php',
                'example\\framework\\event\\dummyevent' => '/DummyEvent.php',
                'example\\framework\\event\\dummyeventmapping' => '/DummyEventMapping.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
