<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'example\\caledonia\\domain\\amountmustnotbecomenegativeexception' => '/domain/exceptions/AmountMustNotBecomeNegativeException.php',
                'example\\caledonia\\domain\\amountmustnotbenegativeexception' => '/domain/exceptions/AmountMustNotBeNegativeException.php',
                'example\\caledonia\\domain\\bread' => '/domain/goods/Bread.php',
                'example\\caledonia\\domain\\cheese' => '/domain/goods/Cheese.php',
                'example\\caledonia\\domain\\exception' => '/domain/exceptions/Exception.php',
                'example\\caledonia\\domain\\good' => '/domain/goods/Good.php',
                'example\\caledonia\\domain\\grain' => '/domain/goods/Grain.php',
                'example\\caledonia\\domain\\market' => '/domain/market/Market.php',
                'example\\caledonia\\domain\\milk' => '/domain/goods/Milk.php',
                'example\\caledonia\\domain\\money' => '/domain/player/Money.php',
                'example\\caledonia\\domain\\namemustnotbeemptyexception' => '/domain/exceptions/NameMustNotBeEmptyException.php',
                'example\\caledonia\\domain\\player' => '/domain/player/Player.php',
                'example\\caledonia\\domain\\price' => '/domain/market/Price.php',
                'example\\caledonia\\domain\\pricemustbepositiveexception' => '/domain/exceptions/PriceMustBePositiveException.php',
                'example\\caledonia\\domain\\pricetable' => '/domain/market/PriceTable.php',
                'example\\caledonia\\domain\\whisky' => '/domain/goods/Whisky.php',
                'example\\caledonia\\domain\\wool' => '/domain/goods/Wool.php',
                'example\\framework\\database\\database' => '/framework/database/connection/Database.php',
                'example\\framework\\database\\databaseexception' => '/framework/exceptions/DatabaseException.php',
                'example\\framework\\database\\mysqldatabase' => '/framework/database/connection/MysqlDatabase.php',
                'example\\framework\\database\\mysqldatabaseconfiguration' => '/framework/database/connection/MysqlDatabaseConfiguration.php',
                'example\\framework\\event\\event' => '/framework/event/Event.php',
                'example\\framework\\event\\eventcollection' => '/framework/event/EventCollection.php',
                'example\\framework\\event\\eventcollectioniterator' => '/framework/event/EventCollectionIterator.php',
                'example\\framework\\exception' => '/framework/exceptions/Exception.php',
                'example\\framework\\library\\invaliduuidexception' => '/framework/exceptions/InvalidUuidException.php',
                'example\\framework\\library\\randomuuidgenerator' => '/framework/uuid/RandomUuidGenerator.php',
                'example\\framework\\library\\uuid' => '/framework/uuid/Uuid.php',
                'example\\framework\\library\\uuidgenerator' => '/framework/uuid/UuidGenerator.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
